name: the_animator
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: 8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  flutter_localizations:
    sdk: flutter
  freezed_annotation: 2.4.1
  hydrated_bloc: 9.1.3
  intl: 0.18.0
  path_provider: 2.1.2
  

dev_dependencies:
  bloc_test: 9.1.2
  build_runner: 2.4.8
  flutter_test:
    sdk: flutter
  freezed: 2.4.6
  json_serializable: 6.7.1
  mocktail: 0.3.0
  very_good_analysis: 5.0.0

flutter:
  uses-material-design: true
  generate: true
